# -*- coding: utf-8 -*-
"""Starlink_BBRv3_QB_new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105X2wiTP7XGHsy_UeBGIvaa1uXWhIqwD
"""

from google.colab import drive

drive.mount('/content/drive')

import json
import re
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt

BASE_FOLDER = Path("/content/drive/MyDrive/downlink-competitive-logs")

OUTPUT_FOLDER = Path("/content/drive/MyDrive/processed_output")

OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)

print("Input folder exists:", BASE_FOLDER.exists())
print("Input folder:", BASE_FOLDER)
print("Output folder:", OUTPUT_FOLDER)

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# city_folders = sorted(folder for folder in BASE_FOLDER.iterdir() if folder.is_dir())
# 
# print("Cities found:")
# 
# for city_folder in city_folders:
#     json_files = list(city_folder.glob("bbr*.json"))
# 
#     print(f"{city_folder.name}: " f"{len(json_files)} BBRv3 JSON files")
# 
# def load_json_objects(json_path: Path) -> list[dict]:
#     with json_path.open("r", encoding="utf-8-sig") as file:
#         raw_text = file.read()
# 
#     decoder = json.JSONDecoder()
#     objects = []
#     position = 0
#     text_length = len(raw_text)
# 
#     while position < text_length:
# 
#         next_object_start = raw_text.find("{", position)
# 
#         if next_object_start == -1:
#             break
#         try:
#             json_object, next_position = decoder.raw_decode(raw_text, next_object_start)
#         except json.JSONDecodeError:
#             position = next_object_start + 1
#             continue
# 
#         if isinstance(json_object, dict):
#             objects.append(json_object)
# 
#         position = next_position
# 
#     if not objects:
#         raise ValueError(f"No valid JSON object could be read from " f"{json_path.name}")
#     return objects
# 
# def extract_run_data(json_path: Path, city: str, minimum_duration: float = 0.90, maximum_duration: float = 1.10, max_intervals: int = 300) -> pd.DataFrame:
#     try:
#         json_objects = load_json_objects(json_path)
#     except (OSError, ValueError) as error:
#         print(f"Could not process {json_path.name}: {error}")
#         return pd.DataFrame()
#     if not json_objects:
#         print(f"No readable JSON objects found in {json_path.name}")
#         return pd.DataFrame()
# 
#     run_match = re.search(r"run(\d+)",json_path.stem, flags=re.IGNORECASE)
# 
#     run_number = (int(run_match.group(1)) if run_match else None)
# 
#     required_fields = [
#         "start",
#         "end",
#         "seconds",
#         "bits_per_second",
#         "retransmits",
#         "snd_cwnd",
#         "snd_wnd",
#         "rtt",
#         "rttvar"
#     ]
# 
#     records = []
# 
#     for json_object_number, data in enumerate(json_objects, start=1):
#         intervals = data.get("intervals", [])
# 
#         for original_interval_number, interval in enumerate(intervals, start=1):
#             streams = interval.get("streams", [])
#             if not streams:
#                 continue
#             stream = streams[0]
# 
#             if stream.get("omitted", False):
#                 continue
#             if any(
#                 stream.get(field) is None for field in required_fields):
#                 continue
#             duration_s = float(stream["seconds"])
# 
#             if not (minimum_duration <= duration_s <= maximum_duration):
#                 continue
# 
#             records.append({
#                 "city": city,
#                 "run_number": run_number,
#                 "run_id": f"{city}_run{run_number}",
#                 "source_file": json_path.name,
#                 "json_object_number": json_object_number,
#                 "original_interval_number": original_interval_number,
# 
#                 "start_time_s": float(stream["start"]),
#                 "end_time_s": float(stream["end"]),
#                 "duration_s": duration_s,
# 
#                 "throughput_mbps": (float(stream["bits_per_second"])/ 1_000_000),
# 
#                 "rtt_ms": (float(stream["rtt"])/ 1_000),
# 
#                 "rtt_variance_ms": (float(stream["rttvar"])/ 1_000),
# 
#                 "retransmissions": int(stream["retransmits"]),
# 
#                 "snd_cwnd_kib": (float(stream["snd_cwnd"])/ 1_024),
# 
#                 "snd_wnd_kib": (float(stream["snd_wnd"])/ 1_024)
#             })
# 
#     run_df = pd.DataFrame(records)
# 
#     if run_df.empty:
#         return run_df
# 
#     run_df = (
#         run_df
#         .sort_values(
#             by=[
#                 "json_object_number",
#                 "start_time_s",
#                 "end_time_s"
#             ]
#         )
#         .drop_duplicates(
#             subset=[
#                 "json_object_number",
#                 "start_time_s",
#                 "end_time_s"
#             ]
#         )
#         .reset_index(drop=True)
#     )
# 
#     if len(run_df) > max_intervals:
#         run_df = (run_df.iloc[:max_intervals].copy().reset_index(drop=True))
# 
#     run_df["interval_number"] = range(1,len(run_df) + 1)
# 
#     column_order = [
#         "city",
#         "run_number",
#         "run_id",
#         "source_file",
#         "json_object_number",
#         "interval_number",
#         "original_interval_number",
#         "start_time_s",
#         "end_time_s",
#         "duration_s",
#         "throughput_mbps",
#         "rtt_ms",
#         "rtt_variance_ms",
#         "retransmissions",
#         "snd_cwnd_kib",
#         "snd_wnd_kib"
#     ]
# 
#     return run_df[column_order]
# 
# test_file = (BASE_FOLDER / "London" / "bbr_London__REV_run1.json")
# 
# test_df = extract_run_data(json_path=test_file, city="London")
# 
# print("Valid intervals:", len(test_df))
# print("JSON objects found:", test_df["json_object_number"].nunique() if not test_df.empty else 0)
# 
# print("Chronological order preserved:", test_df["start_time_s"].is_monotonic_increasing)
# 
# display(test_df.head())
# display(test_df.tail())
# 
# all_run_dataframes = []
# processing_summary = []
# 
# 
# def get_run_number(path: Path) -> int:
#     match = re.search(r"run(\d+)", path.stem, flags=re.IGNORECASE)
#     return int(match.group(1)) if match else 999
# 
# city_folders = sorted(folder for folder in BASE_FOLDER.iterdir() if folder.is_dir())
# 
# print("Cities found:", [folder.name for folder in city_folders])
# 
# 
# for city_folder in city_folders:
#     city = city_folder.name
# 
#     json_files = sorted(city_folder.glob("bbr*.json"), key=get_run_number)
# 
#     print(f"\nProcessing city: {city}")
#     print(f"Files found: {len(json_files)}")
# 
#     for json_path in json_files:
#         run_df = extract_run_data(json_path=json_path, city=city)
# 
#         if run_df.empty:
#             processing_summary.append({
#                 "city": city,
#                 "run_number": get_run_number(json_path),
#                 "source_file": json_path.name,
#                 "valid_intervals": 0,
#                 "status": "No valid data"
#             })
# 
#             print(f"  {json_path.name}: no valid data")
#             continue
# 
#         all_run_dataframes.append(run_df)
# 
#         processing_summary.append({
#             "city": city,
#             "run_number": run_df["run_number"].iloc[0],
#             "source_file": json_path.name,
#             "valid_intervals": len(run_df),
#             "start_time_s": run_df["start_time_s"].min(),
#             "end_time_s": run_df["end_time_s"].max(),
#             "status": "Processed"
#         })
# 
#         print(f"  {json_path.name}: " f"{len(run_df)} valid intervals")
# 
# if not all_run_dataframes:
#     raise ValueError("No valid interval datasets were created.")
# 
# combined_df = pd.concat(all_run_dataframes, ignore_index=True)
# 
# combined_df = (
#     combined_df
#     .sort_values(
#         by=[
#             "city",
#             "run_number",
#             "json_object_number",
#             "interval_number"
#         ]
#     )
#     .reset_index(drop=True)
# )
# 
# summary_df = pd.DataFrame(processing_summary)
# 
# print("Combined dataset created successfully.")
# print("Combined dataset shape:", combined_df.shape)
# print("Total files processed:", len(summary_df))
# 
# display(combined_df.head(10))
# 
# combined_df.to_csv('output.csv', index=False)
# 
# import numpy as np
# 
# from sklearn.preprocessing import StandardScaler
# 
# INPUT_FEATURES = [
#     "throughput_mbps",
#     "rtt_ms",
#     "rtt_variance_ms",
#     "retransmissions",
#     "snd_cwnd_kib",
#     "snd_wnd_kib"
# ]
# 
# TARGET_FEATURES = [
#     "throughput_mbps",
#     "rtt_ms",
#     "rtt_variance_ms",
#     "retransmissions"
# ]
# 
# WINDOW_SIZE = 10
# 
# print("Input features:", INPUT_FEATURES)
# print("Target features:", TARGET_FEATURES)
# print("Sliding-window size:", WINDOW_SIZE)
# 
# def create_run_sequences(run_df: pd.DataFrame, window_size: int, input_features: list[str], target_features: list[str]):
#     run_df = (run_df.sort_values("interval_number").reset_index(drop=True))
# 
#     input_values = run_df[input_features].to_numpy(dtype=np.float32)
# 
#     target_values = run_df[target_features].to_numpy(dtype=np.float32)
# 
#     X_samples = []
#     y_samples = []
#     metadata = []
# 
#     number_of_intervals = len(run_df)
# 
#     if number_of_intervals <= window_size:
#         return (np.empty((0, window_size, len(input_features)), dtype=np.float32), np.empty((0, len(target_features)), dtype=np.float32), [])
# 
#     for start_index in range(number_of_intervals - window_size):
#         end_index = start_index + window_size
#         target_index = end_index
# 
#         X_window = input_values[start_index:end_index]
#         y_target = target_values[target_index]
# 
#         X_samples.append(X_window)
#         y_samples.append(y_target)
# 
#         metadata.append({"city": run_df.loc[0, "city"], "run_number": int(run_df.loc[0, "run_number"]), "run_id": run_df.loc[0, "run_id"],
#             "json_object_number": int(run_df.loc[0, "json_object_number"]),
#             "window_start_interval": int(
#                 run_df.loc[start_index, "interval_number"]),
#             "window_end_interval": int(run_df.loc[end_index - 1, "interval_number"]),
#             "target_interval": int(
#                 run_df.loc[target_index, "interval_number"]),
#             "target_end_time_s": float(run_df.loc[target_index, "end_time_s"])
#         })
# 
#     return (np.asarray(X_samples, dtype=np.float32),np.asarray(y_samples, dtype=np.float32), metadata)
# 
# demo_run_df = combined_df[(combined_df["city"] == "London") & (combined_df["run_number"] == 1) & (combined_df["json_object_number"] == 1)].copy()
# 
# X_demo, y_demo, demo_metadata = create_run_sequences(run_df=demo_run_df, window_size=WINDOW_SIZE, input_features=INPUT_FEATURES, target_features=TARGET_FEATURES)
# 
# print("Demo input shape:", X_demo.shape)
# print("Demo target shape:", y_demo.shape)
# print("Number of sequence samples:", len(X_demo))
# 
# first_input_sequence = pd.DataFrame(X_demo[0], columns=INPUT_FEATURES)
# 
# print("Input: intervals 1-10")
# display(first_input_sequence)
# 
# first_target = pd.DataFrame([y_demo[0]], columns=TARGET_FEATURES)
# 
# print("Target: interval 11")
# display(first_target)
# 
# display(pd.DataFrame([demo_metadata[0]]))
# 
# display(demo_run_df.loc[demo_run_df["interval_number"] == 11, TARGET_FEATURES])
# 
# all_X_sequences = []
# all_y_targets = []
# all_sequence_metadata = []
# 
# group_columns = ["city", "run_number", "json_object_number"]
# 
# for group_key, run_group in combined_df.groupby(group_columns, sort=True):
#     city, run_number, json_object_number = group_key
#     X_run, y_run, metadata_run = create_run_sequences(run_df=run_group, window_size=WINDOW_SIZE, input_features=INPUT_FEATURES, target_features=TARGET_FEATURES)
# 
#     if len(X_run) == 0:
#         print(f"Skipped {city}, run {run_number}: " "not enough intervals")
#         continue
# 
#     all_X_sequences.append(X_run)
#     all_y_targets.append(y_run)
#     all_sequence_metadata.extend(metadata_run)
# 
#     print(f"{city} run {run_number}: " f"{len(X_run)} sequences")
# 
# if not all_X_sequences:
#     raise ValueError("No sliding-window sequences were generated.")
# 
# X_all = np.concatenate(all_X_sequences,axis=0)
# 
# y_all = np.concatenate(all_y_targets, axis=0)
# 
# sequence_metadata_df = pd.DataFrame(all_sequence_metadata)
# 
# print("Combined sequence dataset created.")
# print("X_all shape:", X_all.shape)
# print("y_all shape:", y_all.shape)
# print("Metadata shape:",sequence_metadata_df.shape)
# 
# assert len(X_all) == len(y_all)
# assert len(X_all) == len(sequence_metadata_df)
# 
# print("Sequence arrays and metadata align:", True)
# 
# print("Unique runs represented:", sequence_metadata_df[["city", "run_number"]].drop_duplicates().shape[0])
# 
# print("\nSequences per run:")
# 
# sequences_per_run = (sequence_metadata_df.groupby(["city", "run_number"]).size().reset_index(name="sequence_count"))
# display(sequences_per_run)
# 
# print("Minimum sequences in one run:", sequences_per_run["sequence_count"].min())
# 
# print("Maximum sequences in one run:", sequences_per_run["sequence_count"].max())
# 
# def assign_dataset_split(run_number: int) -> str:
#     if 1 <= run_number <= 7:
#         return "train"
#     if run_number == 8:
#         return "validation"
#     if run_number in [9, 10]:
#         return "test"
# 
#     raise ValueError(f"Unexpected run number: {run_number}")
# 
# sequence_metadata_df["dataset_split"] = (sequence_metadata_df["run_number"].apply(assign_dataset_split))
# 
# print("Sequence samples per split:")
# 
# display(sequence_metadata_df["dataset_split"].value_counts())
# 
# train_mask = (sequence_metadata_df["dataset_split"].to_numpy() == "train")
# 
# validation_mask = (sequence_metadata_df["dataset_split"].to_numpy() == "validation")
# 
# test_mask = (sequence_metadata_df["dataset_split"].to_numpy() == "test")
# 
# X_train_raw = X_all[train_mask]
# y_train_raw = y_all[train_mask]
# 
# X_validation_raw = X_all[validation_mask]
# 
# y_validation_raw = y_all[validation_mask]
# 
# X_test_raw = X_all[test_mask]
# y_test_raw = y_all[test_mask]
# 
# train_metadata_df = (sequence_metadata_df[train_mask].reset_index(drop=True))
# 
# validation_metadata_df = (sequence_metadata_df[validation_mask].reset_index(drop=True))
# 
# test_metadata_df = (sequence_metadata_df[test_mask].reset_index(drop=True))
# 
# print("Raw dataset shapes:")
# print("X_train_raw:",X_train_raw.shape)
# print("y_train_raw:",y_train_raw.shape)
# print("X_validation_raw:", X_validation_raw.shape)
# print("y_validation_raw:", y_validation_raw.shape)
# print("X_test_raw:", X_test_raw.shape)
# print("y_test_raw:", y_test_raw.shape)
# 
# split_run_check = (sequence_metadata_df[["city", "run_number", "dataset_split"]].drop_duplicates() .sort_values(["city", "run_number"]))
# 
# display(split_run_check)
# 
# run_split_counts = (split_run_check.groupby(["city", "run_number"])["dataset_split"].nunique())
# assert run_split_counts.max() == 1
# 
# print("No run appears in multiple splits:",True)
# 
# number_of_input_features = len(INPUT_FEATURES)
# 
# X_train_2d = X_train_raw.reshape(-1, number_of_input_features)
# 
# input_scaler = StandardScaler()
# input_scaler.fit(X_train_2d)
# 
# def scale_input_sequences(X: np.ndarray, scaler: StandardScaler) -> np.ndarray:
#   original_shape = X.shape
#   X_2d = X.reshape(-1, original_shape[-1])
#   X_scaled_2d = scaler.transform(X_2d)
#   return (X_scaled_2d.reshape(original_shape).astype(np.float32))
# 
# X_train = scale_input_sequences(X_train_raw, input_scaler)
# 
# X_validation = scale_input_sequences(X_validation_raw, input_scaler)
# 
# X_test = scale_input_sequences(X_test_raw,input_scaler)
# 
# target_scaler = StandardScaler()
# 
# target_scaler.fit(y_train_raw)
# 
# y_train = (target_scaler.transform(y_train_raw).astype(np.float32))
# 
# y_validation = (target_scaler.transform(y_validation_raw).astype(np.float32))
# 
# y_test = (target_scaler.transform(y_test_raw).astype(np.float32))
# 
# print("Prepared dataset shapes:")
# 
# print("X_train:", X_train.shape)
# print("y_train:", y_train.shape)
# 
# print("X_validation:", X_validation.shape)
# 
# print("y_validation:",y_validation.shape)
# 
# print("X_test:", X_test.shape)
# print("y_test:", y_test.shape)
# 
# SEQUENCE_OUTPUT_FOLDER = (OUTPUT_FOLDER /"qnn_prepared_data")
# 
# SEQUENCE_OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)
# 
# combined_interval_path = (OUTPUT_FOLDER /"combined_bbrv3_interval_dataset.csv")
# 
# combined_df.to_csv(combined_interval_path, index=False)
# 
# print("Combined interval dataset saved to:")
# 
# print(combined_interval_path)
# 
# sliding_window_df = []
# 
# for i in range(len(X_all)):
# 
#     row = {}
# 
#     flattened = X_all[i].reshape(-1)
# 
#     for j, value in enumerate(flattened):
#         row[f"input_{j+1}"] = value
# 
#     row["target_throughput_mbps"] = y_all[i][0]
#     row["target_rtt_ms"] = y_all[i][1]
#     row["target_rtt_variance_ms"] = y_all[i][2]
#     row["target_retransmissions"] = y_all[i][3]
# 
#     sliding_window_df.append(row)
# 
# sliding_window_df = pd.DataFrame(sliding_window_df)
# 
# sliding_window_df.to_csv(SEQUENCE_OUTPUT_FOLDER /"sliding_window_dataset.csv",index=False)
# 
# print(sliding_window_df.shape)
# display(sliding_window_df.head())

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -q "qiskit~=2.1" "qiskit-machine-learning[torch]~=0.9" pylatexenc
# 
# import copy
# import json
# import math
# import random
# from pathlib import Path
# 
# import matplotlib.pyplot as plt
# import numpy as np
# import pandas as pd
# import torch
# from sklearn.metrics import (
#     accuracy_score,
#     f1_score,
#     mean_absolute_error,
#     mean_squared_error,
#     precision_score,
#     r2_score,
#     recall_score,
# )
# from torch import nn
# from torch.utils.data import DataLoader, TensorDataset
# 
# from qiskit import QuantumCircuit, QuantumRegister
# from qiskit.circuit import ParameterVector
# from qiskit.primitives import StatevectorEstimator, StatevectorSampler
# from qiskit.quantum_info import SparsePauliOp
# from qiskit_machine_learning.algorithms.inference import QBayesian
# from qiskit_machine_learning.connectors import TorchConnector
# from qiskit_machine_learning.neural_networks import EstimatorQNN
# 
# SEED = 42
# random.seed(SEED)
# np.random.seed(SEED)
# torch.manual_seed(SEED)
# 
# QML_OUTPUT = Path(OUTPUT_FOLDER) / "qnn_qbi_results"
# QML_OUTPUT.mkdir(parents=True, exist_ok=True)
# 
# TARGET_NAMES = [
#     "throughput_mbps",
#     "rtt_ms",
#     "rtt_variance_ms",
#     "retransmissions",
# ]
# TARGET_UNITS = ["Mbps", "ms", "ms", "count"]
# 
# MAX_QNN_TRAIN = 900
# MAX_QNN_VALIDATION = 300
# MAX_QNN_TEST = None
# BATCH_SIZE = 16
# MAX_EPOCHS = 30
# PATIENCE = 6
# LEARNING_RATE = 0.005
# 
# def temporal_compression(X: np.ndarray) -> np.ndarray:
#     if X.ndim != 3:
#         raise ValueError(f"Expected a 3-D sequence array, received {X.shape}.")
# 
#     window_mean = X.mean(axis=1)
#     latest_value = X[:, -1, :]
#     trend = X[:, -1, :] - X[:, 0, :]
#     compressed = np.concatenate([window_mean, latest_value, trend], axis=1)
#     angles = np.pi * np.tanh(compressed / 3.0)
#     return angles.astype(np.float32)
# 
# 
# X_train_q = temporal_compression(X_train)
# X_validation_q = temporal_compression(X_validation)
# X_test_q = temporal_compression(X_test)
# 
# print("Quantum input shapes:")
# print("X_train_q:", X_train_q.shape)
# print("X_validation_q:", X_validation_q.shape)
# print("X_test_q:", X_test_q.shape)
# 
# def select_evenly_spaced_indices(n: int, maximum: int | None) -> np.ndarray:
#     if maximum is None or n <= maximum:
#         return np.arange(n)
#     return np.linspace(0, n - 1, num=maximum, dtype=int)
# 
# 
# train_q_idx = select_evenly_spaced_indices(len(X_train_q), MAX_QNN_TRAIN)
# val_q_idx = select_evenly_spaced_indices(len(X_validation_q), MAX_QNN_VALIDATION)
# test_q_idx = select_evenly_spaced_indices(len(X_test_q), MAX_QNN_TEST)
# 
# X_train_q_small = X_train_q[train_q_idx]
# X_val_q_small = X_validation_q[val_q_idx]
# X_test_q_eval = X_test_q[test_q_idx]
# 
# train_current_scaled = target_scaler.transform(
#     X_train_raw[train_q_idx, -1, :4]
# ).astype(np.float32)
# validation_current_scaled = target_scaler.transform(
#     X_validation_raw[val_q_idx, -1, :4]
# ).astype(np.float32)
# test_current_scaled = target_scaler.transform(
#     X_test_raw[test_q_idx, -1, :4]
# ).astype(np.float32)
# 
# y_train_q_small = y_train[train_q_idx] - train_current_scaled
# y_val_q_small = y_validation[val_q_idx] - validation_current_scaled
# 
# y_test_q_eval = y_test[test_q_idx]
# y_test_raw_eval = y_test_raw[test_q_idx]
# test_metadata_eval = test_metadata_df.iloc[test_q_idx].reset_index(drop=True)
# X_test_raw_eval = X_test_raw[test_q_idx]
# 
# def build_estimator_qnn(num_qubits: int = 6, num_encoding_blocks: int = 3,) -> tuple[EstimatorQNN, QuantumCircuit]:
# 
#     num_inputs = num_qubits * num_encoding_blocks
#     num_weights = num_encoding_blocks * num_qubits * 2
# 
#     input_params = ParameterVector("x", num_inputs)
#     weight_params = ParameterVector("theta", num_weights)
#     circuit = QuantumCircuit(num_qubits, name="Starlink_QNN")
# 
#     w = 0
#     for block in range(num_encoding_blocks):
#         offset = block * num_qubits
#         for qubit in range(num_qubits):
#             circuit.ry(input_params[offset + qubit], qubit)
#         for qubit in range(num_qubits):
#             circuit.ry(weight_params[w], qubit)
#             circuit.rz(weight_params[w + 1], qubit)
#             w += 2
#         for qubit in range(num_qubits - 1):
#             circuit.cx(qubit, qubit + 1)
#         circuit.cx(num_qubits - 1, 0)
#         circuit.barrier()
#     observables = []
#     for measured_qubit in range(4):
#         pauli = ["I"] * num_qubits
#         pauli[num_qubits - 1 - measured_qubit] = "Z"
#         observables.append(SparsePauliOp.from_list([("".join(pauli), 1.0)]))
# 
#     estimator = StatevectorEstimator(seed=SEED)
#     qnn = EstimatorQNN(
#         circuit=circuit,
#         estimator=estimator,
#         observables=observables,
#         input_params=list(input_params),
#         weight_params=list(weight_params),
#         input_gradients=True,
#     )
#     return qnn, circuit
# 
# class HybridQNNRegressor(nn.Module):
#     def __init__(self, qnn: EstimatorQNN):
#         super().__init__()
#         initial_weights = 0.1 * np.random.default_rng(SEED).standard_normal(qnn.num_weights)
#         self.quantum_layer = TorchConnector(qnn, initial_weights=initial_weights)
#         self.readout = nn.Linear(4, 4)
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         quantum_values = self.quantum_layer(x)
#         return self.readout(quantum_values.float())
# 
# 
# qnn, qnn_circuit = build_estimator_qnn()
# model = HybridQNNRegressor(qnn)
# 
# print(qnn_circuit.draw(output="text", fold=120))
# print("QNN inputs:", qnn.num_inputs)
# print("QNN trainable quantum weights:", qnn.num_weights)
# 
# 
# QNN_CHECKPOINT_PATH = (
#     Path("/content/hybrid_qnn_state_dict.pt")
# )
# 
# if not QNN_CHECKPOINT_PATH.exists():
#     raise FileNotFoundError(
#         "QNN checkpoint not found. Update QNN_CHECKPOINT_PATH to the location "
#         "of hybrid_qnn_state_dict.pt in Google Drive: "
#         f"{QNN_CHECKPOINT_PATH}"
#     )
# 
# try:
#     saved_state = torch.load(
#         QNN_CHECKPOINT_PATH,
#         map_location="cpu",
#         weights_only=True,
#     )
# except TypeError:
#     saved_state = torch.load(QNN_CHECKPOINT_PATH, map_location="cpu")
# 
# model.load_state_dict(saved_state)
# model.eval()
# print("Loaded QNN checkpoint:", QNN_CHECKPOINT_PATH)
# 
# def predict_scaled(model_: nn.Module, X_: np.ndarray, batch_size: int = 32) -> np.ndarray:
#     model_.eval()
#     outputs = []
#     loader = DataLoader(
#         TensorDataset(torch.tensor(X_, dtype=torch.float32)),
#         batch_size=batch_size,
#         shuffle=False,
#     )
#     with torch.no_grad():
#         for (batch_X,) in loader:
#             outputs.append(model_(batch_X).cpu().numpy())
#     return np.concatenate(outputs, axis=0)
# 
# 
# qnn_test_change_scaled = predict_scaled(model, X_test_q_eval)
# qnn_test_pred_scaled = test_current_scaled + qnn_test_change_scaled
# qnn_test_pred_raw = target_scaler.inverse_transform(qnn_test_pred_scaled)
# 
# 
# qnn_test_pred_raw[:, 0] = np.clip(qnn_test_pred_raw[:, 0], 0, None)
# qnn_test_pred_raw[:, 3] = np.clip(qnn_test_pred_raw[:, 3], 0, None)

from __future__ import annotations

from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from qiskit import QuantumCircuit, QuantumRegister
from qiskit.primitives import StatevectorSampler
from qiskit_machine_learning.algorithms.inference import QBayesian
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)


REQUIRED = [
    "X_train_raw", "y_train_raw", "train_metadata_df",
    "X_validation_raw", "y_validation_raw", "validation_metadata_df",
    "X_test_raw", "y_test_raw", "test_metadata_df",
    "qnn_test_pred_raw", "model", "X_validation_q", "target_scaler",
    "predict_scaled", "OUTPUT_FOLDER",
]
missing = [name for name in REQUIRED if name not in globals()]
if missing:
    raise RuntimeError(
        "Run the silent preprocessing/checkpoint stage first. Missing: "
        + ", ".join(missing)
    )

SEED = globals().get("SEED", 42)
QBI_SHOTS = 8192
QBI_EVIDENCE_THRESHOLD = 0.95
ROLLING_RTT_WINDOW = 120
MIN_RTT_HISTORY = 10
MAX_QBI_INTERVALS_PER_RUN = 30
MIN_OPERATIONAL_COVERAGE = 0.80

QBI_OUTPUT = Path(OUTPUT_FOLDER) / "qbi_network_state_evaluation"
QBI_OUTPUT.mkdir(parents=True, exist_ok=True)

EVIDENCE_NAMES = (
    "LowThroughput",
    "HighQueueDelay",
    "HighRTTVariance",
    "RetransmissionBurst",
)
STATE_NAMES = ("Congestion", "QueueBuildUp", "NetworkDisruption")


validation_current_scaled = target_scaler.transform(
    np.asarray(X_validation_raw[:, -1, :4], dtype=float)
)
qnn_validation_change_scaled = predict_scaled(model, X_validation_q)
qnn_validation_pred_scaled = (
    validation_current_scaled + qnn_validation_change_scaled
)
qnn_validation_pred_raw = target_scaler.inverse_transform(
    qnn_validation_pred_scaled
)
qnn_validation_pred_raw[:, 0] = np.clip(
    qnn_validation_pred_raw[:, 0], 0, None
)
qnn_validation_pred_raw[:, 3] = np.clip(
    qnn_validation_pred_raw[:, 3], 0, None
)


train_current = np.asarray(X_train_raw[:, -1, :4], dtype=float)
train_next = np.asarray(y_train_raw, dtype=float)
validation_current = np.asarray(X_validation_raw[:, -1, :4], dtype=float)
validation_next = np.asarray(y_validation_raw, dtype=float)
test_current = np.asarray(X_test_raw[:, -1, :4], dtype=float)
test_next = np.asarray(y_test_raw, dtype=float)
qnn_validation_next = np.asarray(qnn_validation_pred_raw, dtype=float)
qnn_test_next = np.asarray(qnn_test_pred_raw, dtype=float)

for current, nxt, metadata, split in (
    (train_current, train_next, train_metadata_df, "train"),
    (validation_current, validation_next, validation_metadata_df, "validation"),
    (test_current, test_next, test_metadata_df, "test"),
):
    if not (len(current) == len(nxt) == len(metadata)):
        raise ValueError(f"Misaligned {split} arrays and metadata")

if qnn_validation_next.shape != validation_next.shape:
    raise ValueError("Validation QNN predictions do not match validation targets")
if qnn_test_next.shape != test_next.shape:
    raise ValueError("Test QNN predictions do not match test targets")


def causal_rolling_rtt_base(
    current_values: np.ndarray,
    metadata: pd.DataFrame,
) -> np.ndarray:
    """Calculate a causal rolling Q0.05 RTT floor without future values."""
    frame = metadata.reset_index(drop=True).copy()
    frame["_original_index"] = np.arange(len(frame))
    frame["_current_rtt"] = current_values[:, 1]

    group_columns = [
        column
        for column in ("city", "run_number", "json_object_number")
        if column in frame.columns
    ]
    sort_columns = group_columns + [
        column
        for column in ("target_interval", "target_end_time_s")
        if column in frame.columns
    ]
    frame = frame.sort_values(sort_columns)

    bases = np.empty(len(frame), dtype=float)
    global_floor = float(np.quantile(train_current[:, 1], 0.05))

    grouped = frame.groupby(group_columns, sort=False) if group_columns else [(None, frame)]
    for _, group in grouped:
        rolling_floor = (
            group["_current_rtt"]
            .rolling(
                window=ROLLING_RTT_WINDOW,
                min_periods=MIN_RTT_HISTORY,
            )
            .quantile(0.05)
        )
        expanding_floor = group["_current_rtt"].expanding().quantile(0.05)
        floor = rolling_floor.fillna(expanding_floor).fillna(global_floor)
        bases[group["_original_index"].to_numpy(int)] = floor.to_numpy(float)
    return bases


train_rtt_base = causal_rolling_rtt_base(train_current, train_metadata_df)
validation_rtt_base = causal_rolling_rtt_base(
    validation_current, validation_metadata_df
)
test_rtt_base = causal_rolling_rtt_base(test_current, test_metadata_df)

train_queue_delay = np.maximum(0.0, train_next[:, 1] - train_rtt_base)
validation_queue_delay = np.maximum(
    0.0, validation_next[:, 1] - validation_rtt_base
)
qnn_validation_queue_delay = np.maximum(
    0.0, qnn_validation_next[:, 1] - validation_rtt_base
)
test_queue_delay = np.maximum(0.0, test_next[:, 1] - test_rtt_base)
qnn_test_queue_delay = np.maximum(
    0.0, qnn_test_next[:, 1] - test_rtt_base
)


def unique_sorted(values: Iterable[float]) -> list[float]:
    return sorted({float(value) for value in values if np.isfinite(value)})

CANDIDATES = {
    "throughput_drop_ratio": [0.10, 0.20, 0.30, 0.40, 0.50],
    "severe_throughput_drop_ratio": [0.40, 0.50, 0.60, 0.70],
    "high_queue_delay": unique_sorted([
        0.0,
        np.quantile(train_queue_delay, 0.50),
        np.quantile(train_queue_delay, 0.75),
        np.quantile(train_queue_delay, 0.90),
    ]),
    "high_rtt_variance": unique_sorted([
        2.0, 4.0,
        np.quantile(train_next[:, 2], 0.75),
        np.quantile(train_next[:, 2], 0.90),
    ]),
    "retransmission_burst": unique_sorted([
        10.0, 30.0, 70.0,
        np.quantile(train_next[:, 3], 0.75),
        np.quantile(train_next[:, 3], 0.90),
    ]),
}

absolute_low_throughput = float(np.quantile(train_next[:, 0], 0.05))


def binary_scores(actual: np.ndarray, predicted: np.ndarray) -> dict[str, float]:
    actual = np.asarray(actual, dtype=int)
    predicted = np.asarray(predicted, dtype=int)
    prevalence = float(actual.mean())
    if len(np.unique(actual)) == 2:
        balanced = float(balanced_accuracy_score(actual, predicted))
    else:
        balanced = float("nan")
    return {
        "prevalence": prevalence,
        "predicted_prevalence": float(predicted.mean()),
        "accuracy": float(accuracy_score(actual, predicted)),
        "balanced_accuracy": balanced,
        "precision": float(precision_score(actual, predicted, zero_division=0)),
        "recall": float(recall_score(actual, predicted, zero_division=0)),
        "F1": float(f1_score(actual, predicted, zero_division=0)),
    }


def select_candidate(
    name: str,
    candidates: Iterable[float],
    actual_measure: np.ndarray,
    predicted_measure: np.ndarray,
    comparison: str = "ge",
) -> tuple[float, pd.DataFrame]:
    rows = []
    for threshold in candidates:
        if comparison == "ge":
            actual = actual_measure >= threshold
            predicted = predicted_measure >= threshold
        elif comparison == "gt":
            actual = actual_measure > threshold
            predicted = predicted_measure > threshold
        else:
            raise ValueError(f"Unsupported comparison: {comparison}")
        row = {"parameter": name, "candidate": float(threshold)}
        row.update(binary_scores(actual, predicted))
        rows.append(row)

    table = pd.DataFrame(rows)
    eligible = table[
        table["prevalence"].between(0.05, 0.95)
        & table["balanced_accuracy"].notna()
    ]
    if eligible.empty:
        eligible = table[table["balanced_accuracy"].notna()]
    if eligible.empty:
        raise ValueError(f"No valid validation candidate for {name}")

    selected_row = eligible.sort_values(
        ["balanced_accuracy", "F1", "candidate"],
        ascending=[False, False, True],
    ).iloc[0]
    return float(selected_row["candidate"]), table


validation_actual_drop = np.maximum(
    0.0,
    (validation_current[:, 0] - validation_next[:, 0])
    / np.maximum(validation_current[:, 0], 1e-6),
)
validation_predicted_drop = np.maximum(
    0.0,
    (validation_current[:, 0] - qnn_validation_next[:, 0])
    / np.maximum(validation_current[:, 0], 1e-6),
)

selected = {}
sensitivity_tables = []

selected["throughput_drop_ratio"], table = select_candidate(
    "throughput_drop_ratio",
    CANDIDATES["throughput_drop_ratio"],
    validation_actual_drop,
    validation_predicted_drop,
)
sensitivity_tables.append(table)

selected["severe_throughput_drop_ratio"], table = select_candidate(
    "severe_throughput_drop_ratio",
    CANDIDATES["severe_throughput_drop_ratio"],
    validation_actual_drop,
    validation_predicted_drop,
)
sensitivity_tables.append(table)

selected["high_queue_delay"], table = select_candidate(
    "high_queue_delay",
    CANDIDATES["high_queue_delay"],
    validation_queue_delay,
    qnn_validation_queue_delay,
    comparison="gt",
)
sensitivity_tables.append(table)

selected["high_rtt_variance"], table = select_candidate(
    "high_rtt_variance",
    CANDIDATES["high_rtt_variance"],
    validation_next[:, 2],
    qnn_validation_next[:, 2],
)
sensitivity_tables.append(table)

selected["retransmission_burst"], table = select_candidate(
    "retransmission_burst",
    CANDIDATES["retransmission_burst"],
    validation_next[:, 3],
    qnn_validation_next[:, 3],
)
sensitivity_tables.append(table)

THRESHOLDS = {
    **selected,
    "absolute_low_throughput": absolute_low_throughput,
}

sensitivity_df = pd.concat(sensitivity_tables, ignore_index=True)
sensitivity_df["selected"] = sensitivity_df.apply(
    lambda row: bool(np.isclose(
        row["candidate"], THRESHOLDS[row["parameter"]]
    )),
    axis=1,
)
sensitivity_df.to_csv(
    QBI_OUTPUT / "run8_threshold_sensitivity.csv", index=False
)

threshold_selection_df = pd.DataFrame([
    {
        "component": "RTT baseline",
        "selected_value": "rolling Q0.05 over 120 prior/current intervals",
        "selection_basis": "fixed causal rolling baseline definition",
    },
    {
        "component": "queue delay",
        "selected_value": "max(0, RTT - RTTbase)",
        "selection_basis": "calculated from RTT and the causal RTT baseline",
    },
    {
        "component": "absolute_low_throughput",
        "selected_value": absolute_low_throughput,
        "selection_basis": "training Runs 1-7 fifth percentile",
    },
    *[
        {
            "component": key,
            "selected_value": value,
            "selection_basis": "selected on validation Run 8 from candidate values",
        }
        for key, value in selected.items()
    ],
])
threshold_selection_df.to_csv(
    QBI_OUTPUT / "threshold_selection.csv", index=False
)

print("Selected thresholds (Run 8 only; Runs 9-10 untouched):")
display(threshold_selection_df)
print("\nThreshold sensitivity results:")
display(sensitivity_df.round(5))


def create_evidence(
    current_values: np.ndarray,
    next_values: np.ndarray,
    queue_delay: np.ndarray,
) -> np.ndarray:
    drop = (
        (current_values[:, 0] - next_values[:, 0])
        / np.maximum(current_values[:, 0], 1e-6)
    )
    return np.column_stack([
        (drop >= THRESHOLDS["throughput_drop_ratio"])
        | (next_values[:, 0] <= THRESHOLDS["absolute_low_throughput"]),
        queue_delay > THRESHOLDS["high_queue_delay"],
        next_values[:, 2] >= THRESHOLDS["high_rtt_variance"],
        next_values[:, 3] >= THRESHOLDS["retransmission_burst"],
    ]).astype(np.int8)


def create_proxy_states(
    current_values: np.ndarray,
    next_values: np.ndarray,
    evidence: np.ndarray,
) -> np.ndarray:
    drop = (
        (current_values[:, 0] - next_values[:, 0])
        / np.maximum(current_values[:, 0], 1e-6)
    )
    low, queue, variance, retransmission = evidence.T.astype(bool)
    queue_build_up = queue
    congestion = queue & (low | retransmission)
    disruption = (
        (drop >= THRESHOLDS["severe_throughput_drop_ratio"])
        | (next_values[:, 0] <= THRESHOLDS["absolute_low_throughput"])
    ) & variance
    return np.column_stack([
        congestion, queue_build_up, disruption
    ]).astype(np.int8)


train_evidence = create_evidence(
    train_current, train_next, train_queue_delay
)
validation_actual_evidence = create_evidence(
    validation_current, validation_next, validation_queue_delay
)
validation_qnn_evidence = create_evidence(
    validation_current, qnn_validation_next, qnn_validation_queue_delay
)
test_actual_evidence = create_evidence(
    test_current, test_next, test_queue_delay
)
test_qnn_evidence = create_evidence(
    test_current, qnn_test_next, qnn_test_queue_delay
)

train_states = create_proxy_states(train_current, train_next, train_evidence)
validation_states = create_proxy_states(
    validation_current, validation_next, validation_actual_evidence
)
test_states = create_proxy_states(
    test_current, test_next, test_actual_evidence
)


def laplace_probability(successes: int, total: int) -> float:
    return float((successes + 1.0) / (total + 2.0))


initial_priors = {}
evidence_likelihoods = {}
for state_index, state_name in enumerate(STATE_NAMES):
    labels = train_states[:, state_index]
    initial_priors[state_name] = laplace_probability(
        int(labels.sum()), len(labels)
    )
    evidence_likelihoods[state_name] = {}
    for evidence_index, evidence_name in enumerate(EVIDENCE_NAMES):
        for state_value in (0, 1):
            mask = labels == state_value
            evidence_likelihoods[state_name][
                (evidence_name, state_value)
            ] = laplace_probability(
                int(train_evidence[mask, evidence_index].sum()),
                int(mask.sum()),
            )


def exact_posterior(
    state_name: str,
    evidence_pattern: np.ndarray,
) -> float:
    prior = initial_priors[state_name]
    numerator = prior
    alternative = 1.0 - prior
    for value, evidence_name in zip(evidence_pattern, EVIDENCE_NAMES):
        p1 = evidence_likelihoods[state_name][(evidence_name, 1)]
        p0 = evidence_likelihoods[state_name][(evidence_name, 0)]
        numerator *= p1 if value else 1.0 - p1
        alternative *= p0 if value else 1.0 - p0
    denominator = numerator + alternative
    return float(numerator / denominator) if denominator else prior


validation_exact = np.column_stack([
    [exact_posterior(state, row) for row in validation_qnn_evidence]
    for state in STATE_NAMES
])

decision_thresholds = {}
confidence_thresholds = {}
validation_policy_rows = []

for state_index, state_name in enumerate(STATE_NAMES):
    actual = validation_states[:, state_index]
    posterior = validation_exact[:, state_index]

    decision_rows = []
    for threshold in np.arange(0.30, 0.71, 0.05):
        predicted = (posterior >= threshold).astype(int)
        row = {
            "state": state_name,
            "policy": "decision",
            "threshold": float(threshold),
            "coverage": 1.0,
        }
        row.update(binary_scores(actual, predicted))
        decision_rows.append(row)
    decision_table = pd.DataFrame(decision_rows)
    best_decision = decision_table.sort_values(
        ["balanced_accuracy", "F1", "threshold"],
        ascending=[False, False, True],
    ).iloc[0]
    decision_thresholds[state_name] = float(best_decision["threshold"])
    validation_policy_rows.extend(decision_rows)

    predicted = (
        posterior >= decision_thresholds[state_name]
    ).astype(int)
    confidence = np.maximum(posterior, 1.0 - posterior)
    confidence_rows = []
    for threshold in np.arange(0.50, 0.96, 0.05):
        accepted = confidence >= threshold
        if not accepted.any():
            continue
        scores = binary_scores(actual[accepted], predicted[accepted])
        confidence_rows.append({
            "state": state_name,
            "policy": "confidence",
            "threshold": float(threshold),
            "coverage": float(accepted.mean()),
            **scores,
        })
    confidence_table = pd.DataFrame(confidence_rows)
    eligible = confidence_table[
        confidence_table["coverage"] >= MIN_OPERATIONAL_COVERAGE
    ]
    if eligible.empty:
        eligible = confidence_table.sort_values(
            "coverage", ascending=False
        ).head(1)
    best_confidence = eligible.sort_values(
        ["balanced_accuracy", "accuracy", "coverage"],
        ascending=[False, False, False],
    ).iloc[0]
    confidence_thresholds[state_name] = float(
        best_confidence["threshold"]
    )
    validation_policy_rows.extend(confidence_rows)

validation_policy_df = pd.DataFrame(validation_policy_rows)
validation_policy_df.to_csv(
    QBI_OUTPUT / "run8_decision_confidence_sensitivity.csv", index=False
)

print("\nRun 8 selected decision thresholds:", decision_thresholds)
print("Run 8 selected confidence thresholds:", confidence_thresholds)


def probability_to_angle(probability: float) -> float:
    probability = float(np.clip(probability, 1e-8, 1.0 - 1e-8))
    return float(2.0 * np.arcsin(np.sqrt(probability)))


def build_qbi_circuit(state_name: str) -> QuantumCircuit:
    state_register = QuantumRegister(1, name=state_name)
    evidence_registers = [
        QuantumRegister(1, name=name) for name in EVIDENCE_NAMES
    ]
    circuit = QuantumCircuit(
        state_register, *evidence_registers, name=f"{state_name}_QBI"
    )
    state_qubit = state_register[0]
    circuit.ry(
        probability_to_angle(initial_priors[state_name]), state_qubit
    )
    for register, evidence_name in zip(evidence_registers, EVIDENCE_NAMES):
        circuit.ry(
            probability_to_angle(
                evidence_likelihoods[state_name][(evidence_name, 0)]
            ),
            register[0],
        )
    for register, evidence_name in zip(evidence_registers, EVIDENCE_NAMES):
        p0 = evidence_likelihoods[state_name][(evidence_name, 0)]
        p1 = evidence_likelihoods[state_name][(evidence_name, 1)]
        circuit.cry(
            probability_to_angle(p1) - probability_to_angle(p0),
            state_qubit,
            register[0],
        )
    return circuit


sampler = StatevectorSampler(default_shots=QBI_SHOTS, seed=SEED)
qbi_circuits = {
    state: build_qbi_circuit(state) for state in STATE_NAMES
}


def qiskit_posterior(
    state_name: str,
    evidence_pattern: np.ndarray,
) -> tuple[float, bool]:
    model_qbi = QBayesian(
        circuit=qbi_circuits[state_name], sampler=sampler
    )
    model_qbi.threshold = QBI_EVIDENCE_THRESHOLD
    evidence = {
        name: int(value)
        for name, value in zip(EVIDENCE_NAMES, evidence_pattern)
    }
    posterior = float(
        model_qbi.inference(query={state_name: 1}, evidence=evidence)
    )
    return posterior, bool(model_qbi.converged)


def selected_test_indices(metadata: pd.DataFrame) -> list[int]:
    frame = metadata.reset_index(drop=True).copy()
    frame["_index"] = np.arange(len(frame))
    group_columns = [
        c for c in ("city", "run_number") if c in frame.columns
    ]
    selected_indices = []
    for _, group in frame.groupby(group_columns, sort=True):
        indices = group["_index"].to_numpy(int)
        if (
            MAX_QBI_INTERVALS_PER_RUN is not None
            and len(indices) > MAX_QBI_INTERVALS_PER_RUN
        ):
            positions = np.linspace(
                0,
                len(indices) - 1,
                MAX_QBI_INTERVALS_PER_RUN,
                dtype=int,
            )
            indices = indices[positions]
        selected_indices.extend(indices.tolist())
    return selected_indices


records = []
for sample_index in selected_test_indices(test_metadata_df):
    row = test_metadata_df.iloc[sample_index].to_dict()
    evidence_pattern = test_qnn_evidence[sample_index]
    for evidence_index, evidence_name in enumerate(EVIDENCE_NAMES):
        row[f"predicted_evidence_{evidence_name}"] = int(
            evidence_pattern[evidence_index]
        )
        row[f"actual_evidence_{evidence_name}"] = int(
            test_actual_evidence[sample_index, evidence_index]
        )

    for state_index, state_name in enumerate(STATE_NAMES):
        qbi_p, converged = qiskit_posterior(
            state_name, evidence_pattern
        )
        exact_p = exact_posterior(state_name, evidence_pattern)
        decision_threshold = decision_thresholds[state_name]
        confidence_threshold = confidence_thresholds[state_name]
        confidence = max(qbi_p, 1.0 - qbi_p)
        row[f"actual_{state_name}"] = int(
            test_states[sample_index, state_index]
        )
        row[f"posterior_{state_name}"] = qbi_p
        row[f"exact_posterior_{state_name}"] = exact_p
        row[f"converged_{state_name}"] = converged
        row[f"decision_threshold_{state_name}"] = decision_threshold
        row[f"confidence_threshold_{state_name}"] = confidence_threshold
        row[f"predicted_{state_name}"] = int(
            qbi_p >= decision_threshold
        )
        row[f"confidence_{state_name}"] = confidence
        row[f"accepted_{state_name}"] = bool(
            converged and confidence >= confidence_threshold
        )
    records.append(row)

results_df = pd.DataFrame(records)
results_df.to_csv(QBI_OUTPUT / "qbi_test_interval_results.csv", index=False)


metric_rows = []
confusion_values = {}
for state_name in STATE_NAMES:
    actual = results_df[f"actual_{state_name}"].to_numpy(int)
    predicted = results_df[f"predicted_{state_name}"].to_numpy(int)
    posterior = results_df[f"posterior_{state_name}"].to_numpy(float)
    exact = results_df[f"exact_posterior_{state_name}"].to_numpy(float)
    accepted = results_df[f"accepted_{state_name}"].to_numpy(bool)
    scores = binary_scores(actual, predicted)
    prevalence = float(actual.mean())
    majority = max(prevalence, 1.0 - prevalence)
    brier = float(np.mean((posterior - actual) ** 2))
    prevalence_brier = prevalence * (1.0 - prevalence)
    confusion_values[state_name] = confusion_matrix(
        actual, predicted, labels=[0, 1]
    )
    metric_rows.append({
        "state": state_name,
        **scores,
        "majority_baseline": majority,
        "accuracy_gain": scores["accuracy"] - majority,
        "Brier_score": brier,
        "Brier_skill_vs_prevalence": (
            1.0 - brier / prevalence_brier
            if prevalence_brier > 0 else np.nan
        ),
        "QBI_vs_exact_MAE": float(np.mean(np.abs(posterior - exact))),
        "converged_fraction": float(
            results_df[f"converged_{state_name}"].mean()
        ),
        "operational_coverage": float(accepted.mean()),
        "fallback_fraction": float(1.0 - accepted.mean()),
        "accepted_decision_accuracy": (
            float(accuracy_score(actual[accepted], predicted[accepted]))
            if accepted.any() else np.nan
        ),
        "decision_threshold": decision_thresholds[state_name],
        "confidence_threshold": confidence_thresholds[state_name],
    })

metrics_df = pd.DataFrame(metric_rows)
metrics_df.to_csv(QBI_OUTPUT / "qbi_test_metrics.csv", index=False)
print("\nFinal QBI results on untouched Runs 9-10:")
display(metrics_df.round(5))


figure, axes = plt.subplots(1, 3, figsize=(15, 4.5))
for axis, state_name in zip(axes, STATE_NAMES):
    matrix = confusion_values[state_name]
    image = axis.imshow(matrix, cmap="Blues")
    for row_index in range(2):
        for column_index in range(2):
            axis.text(
                column_index,
                row_index,
                str(matrix[row_index, column_index]),
                ha="center",
                va="center",
            )
    axis.set_title(state_name)
    axis.set_xticks([0, 1], ["Absent", "Present"])
    axis.set_yticks([0, 1], ["Absent", "Present"])
    axis.set_xlabel("QBI operational-proxy decision")
    axis.set_ylabel("Actual operational-proxy state")
figure.suptitle("QNN-driven QBI confusion matrices")
figure.tight_layout()
figure.savefig(QBI_OUTPUT / "qbi_confusion_matrices.png", dpi=200)
plt.show()


figure, axes = plt.subplots(1, 3, figsize=(15, 4.5))
for axis, state_name in zip(axes, STATE_NAMES):
    exact = results_df[f"exact_posterior_{state_name}"].to_numpy(float)
    qbi = results_df[f"posterior_{state_name}"].to_numpy(float)
    axis.scatter(exact, qbi, alpha=0.6)
    axis.plot([0, 1], [0, 1], "k--")
    axis.set_xlim(-0.02, 1.02)
    axis.set_ylim(-0.02, 1.02)
    axis.set_title(state_name)
    axis.set_xlabel("Exact Bayesian posterior")
    axis.set_ylabel("Qiskit QBI posterior")
figure.suptitle("Qiskit posterior verification")
figure.tight_layout()
figure.savefig(QBI_OUTPUT / "qbi_exact_verification.png", dpi=200)
plt.show()


print("\nSaved QBI evaluation outputs to:")
print(QBI_OUTPUT)