# -*- coding: utf-8 -*-
"""Starlink_BBRv3_Implementation_new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGHjsHjA_59g_w0C-gTVEg0jjM9zkoTo
"""

from google.colab import drive

drive.mount('/content/drive')

import json
import re
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt

BASE_FOLDER = Path("/content/drive/MyDrive/downlink-competitive-logs")

OUTPUT_FOLDER = Path("/content/drive/MyDrive/processed_output")

OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)

print("Input folder exists:", BASE_FOLDER.exists())
print("Input folder:", BASE_FOLDER)
print("Output folder:", OUTPUT_FOLDER)

city_folders = sorted(folder for folder in BASE_FOLDER.iterdir() if folder.is_dir())

print("Cities found:")

for city_folder in city_folders:
    json_files = list(city_folder.glob("bbr*.json"))

    print(f"{city_folder.name}: " f"{len(json_files)} BBRv3 JSON files")

def load_json_objects(json_path: Path) -> list[dict]:
    with json_path.open("r", encoding="utf-8-sig") as file:
        raw_text = file.read()

    decoder = json.JSONDecoder()
    objects = []
    position = 0
    text_length = len(raw_text)

    while position < text_length:

        next_object_start = raw_text.find("{", position)

        if next_object_start == -1:
            break
        try:
            json_object, next_position = decoder.raw_decode(raw_text, next_object_start)
        except json.JSONDecodeError:
            position = next_object_start + 1
            continue

        if isinstance(json_object, dict):
            objects.append(json_object)

        position = next_position

    if not objects:
        raise ValueError(f"No valid JSON object could be read from " f"{json_path.name}")
    return objects

def extract_run_data(json_path: Path, city: str, minimum_duration: float = 0.90, maximum_duration: float = 1.10, max_intervals: int = 300) -> pd.DataFrame:
    try:
        json_objects = load_json_objects(json_path)
    except (OSError, ValueError) as error:
        print(f"Could not process {json_path.name}: {error}")
        return pd.DataFrame()
    if not json_objects:
        print(f"No readable JSON objects found in {json_path.name}")
        return pd.DataFrame()

    run_match = re.search(r"run(\d+)",json_path.stem, flags=re.IGNORECASE)

    run_number = (int(run_match.group(1)) if run_match else None)

    required_fields = [
        "start",
        "end",
        "seconds",
        "bits_per_second",
        "retransmits",
        "snd_cwnd",
        "snd_wnd",
        "rtt",
        "rttvar"
    ]

    records = []

    for json_object_number, data in enumerate(json_objects, start=1):
        intervals = data.get("intervals", [])

        for original_interval_number, interval in enumerate(intervals, start=1):
            streams = interval.get("streams", [])
            if not streams:
                continue
            stream = streams[0]

            if stream.get("omitted", False):
                continue
            if any(
                stream.get(field) is None for field in required_fields):
                continue
            duration_s = float(stream["seconds"])

            if not (minimum_duration <= duration_s <= maximum_duration):
                continue

            records.append({
                "city": city,
                "run_number": run_number,
                "run_id": f"{city}_run{run_number}",
                "source_file": json_path.name,
                "json_object_number": json_object_number,
                "original_interval_number": original_interval_number,

                "start_time_s": float(stream["start"]),
                "end_time_s": float(stream["end"]),
                "duration_s": duration_s,

                "throughput_mbps": (float(stream["bits_per_second"])/ 1_000_000),

                "rtt_ms": (float(stream["rtt"])/ 1_000),

                "rtt_variance_ms": (float(stream["rttvar"])/ 1_000),

                "retransmissions": int(stream["retransmits"]),

                "snd_cwnd_kib": (float(stream["snd_cwnd"])/ 1_024),

                "snd_wnd_kib": (float(stream["snd_wnd"])/ 1_024)
            })

    run_df = pd.DataFrame(records)

    if run_df.empty:
        return run_df

    run_df = (
        run_df
        .sort_values(
            by=[
                "json_object_number",
                "start_time_s",
                "end_time_s"
            ]
        )
        .drop_duplicates(
            subset=[
                "json_object_number",
                "start_time_s",
                "end_time_s"
            ]
        )
        .reset_index(drop=True)
    )

    if len(run_df) > max_intervals:
        run_df = (run_df.iloc[:max_intervals].copy().reset_index(drop=True))

    run_df["interval_number"] = range(1,len(run_df) + 1)

    column_order = [
        "city",
        "run_number",
        "run_id",
        "source_file",
        "json_object_number",
        "interval_number",
        "original_interval_number",
        "start_time_s",
        "end_time_s",
        "duration_s",
        "throughput_mbps",
        "rtt_ms",
        "rtt_variance_ms",
        "retransmissions",
        "snd_cwnd_kib",
        "snd_wnd_kib"
    ]

    return run_df[column_order]

test_file = (BASE_FOLDER / "London" / "bbr_London__REV_run1.json")

test_df = extract_run_data(json_path=test_file, city="London")

print("Valid intervals:", len(test_df))
print("JSON objects found:", test_df["json_object_number"].nunique() if not test_df.empty else 0)

print("Chronological order preserved:", test_df["start_time_s"].is_monotonic_increasing)

display(test_df.head())
display(test_df.tail())

all_run_dataframes = []
processing_summary = []


def get_run_number(path: Path) -> int:
    match = re.search(r"run(\d+)", path.stem, flags=re.IGNORECASE)
    return int(match.group(1)) if match else 999

city_folders = sorted(folder for folder in BASE_FOLDER.iterdir() if folder.is_dir())

print("Cities found:", [folder.name for folder in city_folders])


for city_folder in city_folders:
    city = city_folder.name

    json_files = sorted(city_folder.glob("bbr*.json"), key=get_run_number)

    print(f"\nProcessing city: {city}")
    print(f"Files found: {len(json_files)}")

    for json_path in json_files:
        run_df = extract_run_data(json_path=json_path, city=city)

        if run_df.empty:
            processing_summary.append({
                "city": city,
                "run_number": get_run_number(json_path),
                "source_file": json_path.name,
                "valid_intervals": 0,
                "status": "No valid data"
            })

            print(f"  {json_path.name}: no valid data")
            continue

        all_run_dataframes.append(run_df)

        processing_summary.append({
            "city": city,
            "run_number": run_df["run_number"].iloc[0],
            "source_file": json_path.name,
            "valid_intervals": len(run_df),
            "start_time_s": run_df["start_time_s"].min(),
            "end_time_s": run_df["end_time_s"].max(),
            "status": "Processed"
        })

        print(f"  {json_path.name}: " f"{len(run_df)} valid intervals")

if not all_run_dataframes:
    raise ValueError("No valid interval datasets were created.")

combined_df = pd.concat(all_run_dataframes, ignore_index=True)

combined_df = (
    combined_df
    .sort_values(
        by=[
            "city",
            "run_number",
            "json_object_number",
            "interval_number"
        ]
    )
    .reset_index(drop=True)
)

summary_df = pd.DataFrame(processing_summary)

print("Combined dataset created successfully.")
print("Combined dataset shape:", combined_df.shape)
print("Total files processed:", len(summary_df))

display(combined_df.head(10))

combined_df.to_csv('output.csv', index=False)

import numpy as np

from sklearn.preprocessing import StandardScaler

INPUT_FEATURES = [
    "throughput_mbps",
    "rtt_ms",
    "rtt_variance_ms",
    "retransmissions",
    "snd_cwnd_kib",
    "snd_wnd_kib"
]

TARGET_FEATURES = [
    "throughput_mbps",
    "rtt_ms",
    "rtt_variance_ms",
    "retransmissions"
]

WINDOW_SIZE = 10

print("Input features:", INPUT_FEATURES)
print("Target features:", TARGET_FEATURES)
print("Sliding-window size:", WINDOW_SIZE)

def create_run_sequences(run_df: pd.DataFrame, window_size: int, input_features: list[str], target_features: list[str]):
    run_df = (run_df.sort_values("interval_number").reset_index(drop=True))

    input_values = run_df[input_features].to_numpy(dtype=np.float32)

    target_values = run_df[target_features].to_numpy(dtype=np.float32)

    X_samples = []
    y_samples = []
    metadata = []

    number_of_intervals = len(run_df)

    if number_of_intervals <= window_size:
        return (np.empty((0, window_size, len(input_features)), dtype=np.float32), np.empty((0, len(target_features)), dtype=np.float32), [])

    for start_index in range(number_of_intervals - window_size):
        end_index = start_index + window_size
        target_index = end_index

        X_window = input_values[start_index:end_index]
        y_target = target_values[target_index]

        X_samples.append(X_window)
        y_samples.append(y_target)

        metadata.append({"city": run_df.loc[0, "city"], "run_number": int(run_df.loc[0, "run_number"]), "run_id": run_df.loc[0, "run_id"],
            "json_object_number": int(run_df.loc[0, "json_object_number"]),
            "window_start_interval": int(
                run_df.loc[start_index, "interval_number"]),
            "window_end_interval": int(run_df.loc[end_index - 1, "interval_number"]),
            "target_interval": int(
                run_df.loc[target_index, "interval_number"]),
            "target_end_time_s": float(run_df.loc[target_index, "end_time_s"])
        })

    return (np.asarray(X_samples, dtype=np.float32),np.asarray(y_samples, dtype=np.float32), metadata)

demo_run_df = combined_df[(combined_df["city"] == "London") & (combined_df["run_number"] == 1) & (combined_df["json_object_number"] == 1)].copy()

X_demo, y_demo, demo_metadata = create_run_sequences(run_df=demo_run_df, window_size=WINDOW_SIZE, input_features=INPUT_FEATURES, target_features=TARGET_FEATURES)

print("Demo input shape:", X_demo.shape)
print("Demo target shape:", y_demo.shape)
print("Number of sequence samples:", len(X_demo))

first_input_sequence = pd.DataFrame(X_demo[0], columns=INPUT_FEATURES)

print("Input: intervals 1-10")
display(first_input_sequence)

first_target = pd.DataFrame([y_demo[0]], columns=TARGET_FEATURES)

print("Target: interval 11")
display(first_target)

display(pd.DataFrame([demo_metadata[0]]))

display(demo_run_df.loc[demo_run_df["interval_number"] == 11, TARGET_FEATURES])

all_X_sequences = []
all_y_targets = []
all_sequence_metadata = []

group_columns = ["city", "run_number", "json_object_number"]

for group_key, run_group in combined_df.groupby(group_columns, sort=True):
    city, run_number, json_object_number = group_key
    X_run, y_run, metadata_run = create_run_sequences(run_df=run_group, window_size=WINDOW_SIZE, input_features=INPUT_FEATURES, target_features=TARGET_FEATURES)

    if len(X_run) == 0:
        print(f"Skipped {city}, run {run_number}: " "not enough intervals")
        continue

    all_X_sequences.append(X_run)
    all_y_targets.append(y_run)
    all_sequence_metadata.extend(metadata_run)

    print(f"{city} run {run_number}: " f"{len(X_run)} sequences")

if not all_X_sequences:
    raise ValueError("No sliding-window sequences were generated.")

X_all = np.concatenate(all_X_sequences,axis=0)

y_all = np.concatenate(all_y_targets, axis=0)

sequence_metadata_df = pd.DataFrame(all_sequence_metadata)

print("Combined sequence dataset created.")
print("X_all shape:", X_all.shape)
print("y_all shape:", y_all.shape)
print("Metadata shape:",sequence_metadata_df.shape)

assert len(X_all) == len(y_all)
assert len(X_all) == len(sequence_metadata_df)

print("Sequence arrays and metadata align:", True)

print("Unique runs represented:", sequence_metadata_df[["city", "run_number"]].drop_duplicates().shape[0])

print("\nSequences per run:")

sequences_per_run = (sequence_metadata_df.groupby(["city", "run_number"]).size().reset_index(name="sequence_count"))
display(sequences_per_run)

print("Minimum sequences in one run:", sequences_per_run["sequence_count"].min())

print("Maximum sequences in one run:", sequences_per_run["sequence_count"].max())

def assign_dataset_split(run_number: int) -> str:
    if 1 <= run_number <= 7:
        return "train"
    if run_number == 8:
        return "validation"
    if run_number in [9, 10]:
        return "test"

    raise ValueError(f"Unexpected run number: {run_number}")

sequence_metadata_df["dataset_split"] = (sequence_metadata_df["run_number"].apply(assign_dataset_split))

print("Sequence samples per split:")

display(sequence_metadata_df["dataset_split"].value_counts())

train_mask = (sequence_metadata_df["dataset_split"].to_numpy() == "train")

validation_mask = (sequence_metadata_df["dataset_split"].to_numpy() == "validation")

test_mask = (sequence_metadata_df["dataset_split"].to_numpy() == "test")

X_train_raw = X_all[train_mask]
y_train_raw = y_all[train_mask]

X_validation_raw = X_all[validation_mask]

y_validation_raw = y_all[validation_mask]

X_test_raw = X_all[test_mask]
y_test_raw = y_all[test_mask]

train_metadata_df = (sequence_metadata_df[train_mask].reset_index(drop=True))

validation_metadata_df = (sequence_metadata_df[validation_mask].reset_index(drop=True))

test_metadata_df = (sequence_metadata_df[test_mask].reset_index(drop=True))

print("Raw dataset shapes:")
print("X_train_raw:",X_train_raw.shape)
print("y_train_raw:",y_train_raw.shape)
print("X_validation_raw:", X_validation_raw.shape)
print("y_validation_raw:", y_validation_raw.shape)
print("X_test_raw:", X_test_raw.shape)
print("y_test_raw:", y_test_raw.shape)

split_run_check = (sequence_metadata_df[["city", "run_number", "dataset_split"]].drop_duplicates() .sort_values(["city", "run_number"]))

display(split_run_check)

run_split_counts = (split_run_check.groupby(["city", "run_number"])["dataset_split"].nunique())
assert run_split_counts.max() == 1

print("No run appears in multiple splits:",True)

number_of_input_features = len(INPUT_FEATURES)

X_train_2d = X_train_raw.reshape(-1, number_of_input_features)

input_scaler = StandardScaler()
input_scaler.fit(X_train_2d)

def scale_input_sequences(X: np.ndarray, scaler: StandardScaler) -> np.ndarray:
  original_shape = X.shape
  X_2d = X.reshape(-1, original_shape[-1])
  X_scaled_2d = scaler.transform(X_2d)
  return (X_scaled_2d.reshape(original_shape).astype(np.float32))

X_train = scale_input_sequences(X_train_raw, input_scaler)

X_validation = scale_input_sequences(X_validation_raw, input_scaler)

X_test = scale_input_sequences(X_test_raw,input_scaler)

target_scaler = StandardScaler()

target_scaler.fit(y_train_raw)

y_train = (target_scaler.transform(y_train_raw).astype(np.float32))

y_validation = (target_scaler.transform(y_validation_raw).astype(np.float32))

y_test = (target_scaler.transform(y_test_raw).astype(np.float32))

print("Prepared dataset shapes:")

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_validation:", X_validation.shape)

print("y_validation:",y_validation.shape)

print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

SEQUENCE_OUTPUT_FOLDER = (OUTPUT_FOLDER /"qnn_prepared_data")

SEQUENCE_OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)

combined_interval_path = (OUTPUT_FOLDER /"combined_bbrv3_interval_dataset.csv")

combined_df.to_csv(combined_interval_path, index=False)

print("Combined interval dataset saved to:")

print(combined_interval_path)

sliding_window_df = []

for i in range(len(X_all)):

    row = {}

    flattened = X_all[i].reshape(-1)

    for j, value in enumerate(flattened):
        row[f"input_{j+1}"] = value

    row["target_throughput_mbps"] = y_all[i][0]
    row["target_rtt_ms"] = y_all[i][1]
    row["target_rtt_variance_ms"] = y_all[i][2]
    row["target_retransmissions"] = y_all[i][3]

    sliding_window_df.append(row)

sliding_window_df = pd.DataFrame(sliding_window_df)

sliding_window_df.to_csv(SEQUENCE_OUTPUT_FOLDER /"sliding_window_dataset.csv",index=False)

print(sliding_window_df.shape)
display(sliding_window_df.head())

!pip install -q "qiskit~=2.1" "qiskit-machine-learning[torch]~=0.9" pylatexenc

import copy
import json
import math
import random
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score
)
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

from qiskit import QuantumCircuit, QuantumRegister
from qiskit.circuit import ParameterVector
from qiskit.primitives import StatevectorEstimator, StatevectorSampler
from qiskit.quantum_info import SparsePauliOp
from qiskit_machine_learning.algorithms.inference import QBayesian
from qiskit_machine_learning.connectors import TorchConnector
from qiskit_machine_learning.neural_networks import EstimatorQNN

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

QML_OUTPUT = Path(OUTPUT_FOLDER) / "qnn_qbi_results"
QML_OUTPUT.mkdir(parents=True, exist_ok=True)

TARGET_NAMES = [
    "throughput_mbps",
    "rtt_ms",
    "rtt_variance_ms",
    "retransmissions",
]
TARGET_UNITS = ["Mbps", "ms", "ms", "count"]

MAX_QNN_TRAIN = 900
MAX_QNN_VALIDATION = 300
MAX_QNN_TEST = None
BATCH_SIZE = 16
MAX_EPOCHS = 30
PATIENCE = 6
LEARNING_RATE = 0.005

def temporal_compression(X: np.ndarray) -> np.ndarray:
    if X.ndim != 3:
        raise ValueError(f"Expected a 3-D sequence array, received {X.shape}.")

    window_mean = X.mean(axis=1)
    latest_value = X[:, -1, :]
    trend = X[:, -1, :] - X[:, 0, :]
    compressed = np.concatenate([window_mean, latest_value, trend], axis=1)
    angles = np.pi * np.tanh(compressed / 3.0)
    return angles.astype(np.float32)


X_train_q = temporal_compression(X_train)
X_validation_q = temporal_compression(X_validation)
X_test_q = temporal_compression(X_test)

print("Quantum input shapes:")
print("X_train_q:", X_train_q.shape)
print("X_validation_q:", X_validation_q.shape)
print("X_test_q:", X_test_q.shape)

def select_evenly_spaced_indices(n: int, maximum: int | None) -> np.ndarray:
    if maximum is None or n <= maximum:
        return np.arange(n)
    return np.linspace(0, n - 1, num=maximum, dtype=int)


train_q_idx = select_evenly_spaced_indices(len(X_train_q), MAX_QNN_TRAIN)
val_q_idx = select_evenly_spaced_indices(len(X_validation_q), MAX_QNN_VALIDATION)
test_q_idx = select_evenly_spaced_indices(len(X_test_q), MAX_QNN_TEST)

X_train_q_small = X_train_q[train_q_idx]
X_val_q_small = X_validation_q[val_q_idx]
X_test_q_eval = X_test_q[test_q_idx]

train_current_scaled = target_scaler.transform(
    X_train_raw[train_q_idx, -1, :4]
).astype(np.float32)
validation_current_scaled = target_scaler.transform(
    X_validation_raw[val_q_idx, -1, :4]
).astype(np.float32)
test_current_scaled = target_scaler.transform(
    X_test_raw[test_q_idx, -1, :4]
).astype(np.float32)

y_train_q_small = y_train[train_q_idx] - train_current_scaled
y_val_q_small = y_validation[val_q_idx] - validation_current_scaled

y_test_q_eval = y_test[test_q_idx]
y_test_raw_eval = y_test_raw[test_q_idx]
test_metadata_eval = test_metadata_df.iloc[test_q_idx].reset_index(drop=True)
X_test_raw_eval = X_test_raw[test_q_idx]

def build_estimator_qnn(num_qubits: int = 6, num_encoding_blocks: int = 3,) -> tuple[EstimatorQNN, QuantumCircuit]:

    num_inputs = num_qubits * num_encoding_blocks
    num_weights = num_encoding_blocks * num_qubits * 2

    input_params = ParameterVector("x", num_inputs)
    weight_params = ParameterVector("theta", num_weights)
    circuit = QuantumCircuit(num_qubits, name="Starlink_QNN")

    w = 0
    for block in range(num_encoding_blocks):
        offset = block * num_qubits
        for qubit in range(num_qubits):
            circuit.ry(input_params[offset + qubit], qubit)
        for qubit in range(num_qubits):
            circuit.ry(weight_params[w], qubit)
            circuit.rz(weight_params[w + 1], qubit)
            w += 2
        for qubit in range(num_qubits - 1):
            circuit.cx(qubit, qubit + 1)
        circuit.cx(num_qubits - 1, 0)
        circuit.barrier()
    observables = []
    for measured_qubit in range(4):
        pauli = ["I"] * num_qubits
        pauli[num_qubits - 1 - measured_qubit] = "Z"
        observables.append(SparsePauliOp.from_list([("".join(pauli), 1.0)]))

    estimator = StatevectorEstimator(seed=SEED)
    qnn = EstimatorQNN(
        circuit=circuit,
        estimator=estimator,
        observables=observables,
        input_params=list(input_params),
        weight_params=list(weight_params),
        input_gradients=True,
    )
    return qnn, circuit

class HybridQNNRegressor(nn.Module):
    def __init__(self, qnn: EstimatorQNN):
        super().__init__()
        initial_weights = 0.1 * np.random.default_rng(SEED).standard_normal(qnn.num_weights)
        self.quantum_layer = TorchConnector(qnn, initial_weights=initial_weights)
        self.readout = nn.Linear(4, 4)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        quantum_values = self.quantum_layer(x)
        return self.readout(quantum_values.float())


qnn, qnn_circuit = build_estimator_qnn()
model = HybridQNNRegressor(qnn)

print(qnn_circuit.draw(output="text", fold=120))
print("QNN inputs:", qnn.num_inputs)
print("QNN trainable quantum weights:", qnn.num_weights)

train_loader = DataLoader(
    TensorDataset(
        torch.tensor(X_train_q_small, dtype=torch.float32),
        torch.tensor(y_train_q_small, dtype=torch.float32),
    ),
    batch_size=BATCH_SIZE,
    shuffle=True,
)
val_loader = DataLoader(
    TensorDataset(
        torch.tensor(X_val_q_small, dtype=torch.float32),
        torch.tensor(y_val_q_small, dtype=torch.float32),
    ),
    batch_size=BATCH_SIZE,
    shuffle=False,
)

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)

history = {"train_loss": [], "validation_loss": []}
best_state = None
best_validation_loss = math.inf
patience_counter = 0

for epoch in range(1, MAX_EPOCHS + 1):
    print(f"\nStarting epoch {epoch:02d}/{MAX_EPOCHS}...", flush=True)
    model.train()
    train_loss_sum = 0.0
    train_count = 0

    for batch_number, (batch_X, batch_y) in enumerate(train_loader, start=1):
        optimizer.zero_grad()
        predictions = model(batch_X)
        loss = criterion(predictions, batch_y)
        loss.backward()
        optimizer.step()

        train_loss_sum += loss.item() * len(batch_X)
        train_count += len(batch_X)

        print(
            f"Epoch {epoch:02d}/{MAX_EPOCHS} | "
            f"training batch {batch_number}/{len(train_loader)}",
            end="\r",
            flush=True,
        )

    model.eval()
    validation_loss_sum = 0.0
    validation_count = 0
    with torch.no_grad():
        for batch_number, (batch_X, batch_y) in enumerate(val_loader, start=1):
            predictions = model(batch_X)
            loss = criterion(predictions, batch_y)
            validation_loss_sum += loss.item() * len(batch_X)
            validation_count += len(batch_X)

            print(
                f"Epoch {epoch:02d}/{MAX_EPOCHS} | "
                f"validation batch {batch_number}/{len(val_loader)}",
                end="\r",
                flush=True,
            )

    train_loss = train_loss_sum / train_count
    validation_loss = validation_loss_sum / validation_count
    history["train_loss"].append(train_loss)
    history["validation_loss"].append(validation_loss)

    print(
        f"\nEpoch {epoch:02d}/{MAX_EPOCHS} completed | "
        f"train residual MSE={train_loss:.6f} | "
        f"validation residual MSE={validation_loss:.6f}",
        flush=True,
    )

    if validation_loss < best_validation_loss - 1e-5:
        best_validation_loss = validation_loss
        best_state = copy.deepcopy(model.state_dict())
        patience_counter = 0
    else:
        patience_counter += 1
        if patience_counter >= PATIENCE:
            print("Early stopping activated.")
            break

if best_state is None:
    raise RuntimeError("QNN training did not produce a valid model state.")

model.load_state_dict(best_state)
torch.save(model.state_dict(), QML_OUTPUT / "hybrid_qnn_state_dict.pt")

with open(QML_OUTPUT / "qnn_configuration.json", "w", encoding="utf-8") as file:
    json.dump(
        {
            "seed": SEED,
            "qubits": 6,
            "quantum_inputs": 18,
            "quantum_weights": int(qnn.num_weights),
            "window_size": int(X_train.shape[1]),
            "qnn_training_samples": int(len(X_train_q_small)),
            "qnn_validation_samples": int(len(X_val_q_small)),
            "epochs_completed": int(len(history["train_loss"])),
            "prediction_method": "next-interval residual learning",
            "learning_rate": LEARNING_RATE,
            "best_validation_mse_scaled": float(best_validation_loss),
        },
        file,
        indent=2,
    )

plt.figure(figsize=(8, 5))
plt.plot(history["train_loss"], label="Training loss")
plt.plot(history["validation_loss"], label="Validation loss")
plt.xlabel("Epoch")
plt.ylabel("MSE on scaled residual targets")
plt.title("QNN training and validation loss")
plt.legend()
plt.tight_layout()
plt.savefig(QML_OUTPUT / "figure_qnn_loss.png", dpi=300)
plt.show()

def predict_scaled(model_: nn.Module, X_: np.ndarray, batch_size: int = 32) -> np.ndarray:
    model_.eval()
    outputs = []
    loader = DataLoader(
        TensorDataset(torch.tensor(X_, dtype=torch.float32)),
        batch_size=batch_size,
        shuffle=False,
    )
    with torch.no_grad():
        for (batch_X,) in loader:
            outputs.append(model_(batch_X).cpu().numpy())
    return np.concatenate(outputs, axis=0)


validation_current_scaled_full = target_scaler.transform(
    X_validation_raw[:, -1, :4]
).astype(np.float32)


qnn_validation_change_scaled = predict_scaled(model, X_validation_q)
qnn_validation_pred_scaled = (
    validation_current_scaled_full + qnn_validation_change_scaled
)
qnn_validation_pred_raw = target_scaler.inverse_transform(qnn_validation_pred_scaled)
qnn_test_change_scaled = predict_scaled(model, X_test_q_eval)
qnn_test_pred_scaled = test_current_scaled + qnn_test_change_scaled
qnn_test_pred_raw = target_scaler.inverse_transform(qnn_test_pred_scaled)

qnn_validation_pred_raw[:, 0] = np.clip(qnn_validation_pred_raw[:, 0], 0, None)
qnn_validation_pred_raw[:, 3] = np.clip(qnn_validation_pred_raw[:, 3], 0, None)
qnn_test_pred_raw[:, 0] = np.clip(qnn_test_pred_raw[:, 0], 0, None)
qnn_test_pred_raw[:, 3] = np.clip(qnn_test_pred_raw[:, 3], 0, None)


prediction_df = test_metadata_eval.copy()
for index, feature in enumerate(TARGET_NAMES):
    prediction_df[f"actual_bbrv3_{feature}"] = y_test_raw_eval[:, index]
    prediction_df[f"qnn_predicted_{feature}"] = qnn_test_pred_raw[:, index]


CITY_ORDER = [
    "Sydney",
    "Tokyo",
    "London",
    "SaoPaulo",
    "Ohio",
    "Mumbai",
]
actual_cities = list(prediction_df["city"].drop_duplicates())
ordered_cities = [city for city in CITY_ORDER if city in actual_cities]
ordered_cities += [city for city in actual_cities if city not in ordered_cities]
ordered_cities = ordered_cities[:6]

for feature, unit in zip(TARGET_NAMES, TARGET_UNITS):
    fig, axes = plt.subplots(2, 3, figsize=(15, 8))

    for axis, city in zip(axes.flat, ordered_cities):
        city_df = (prediction_df[prediction_df["city"] == city].sort_values(["run_number", "target_interval"]).head(50))

        x_axis = np.arange(1, len(city_df) + 1)
        axis.plot(x_axis, city_df[f"actual_bbrv3_{feature}"], label="Recorded BBRv3",)
        axis.plot(x_axis,city_df[f"qnn_predicted_{feature}"],label="QNN prediction",)
        axis.set_title(city)
        axis.set_xlabel("Test interval")
        axis.set_ylabel(unit)
        axis.grid(alpha=0.3)

    for axis in axes.flat[len(ordered_cities):]:
        axis.set_visible(False)

    handles, labels = axes.flat[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="upper center", ncol=2)

    readable = feature.replace("_", " ").title()
    fig.suptitle(f"Recorded and QNN-predicted competitive-downlink {readable}: " "first 50 held-out intervals", y=0.98,)
    fig.tight_layout(rect=[0, 0, 1, 0.94])
    fig.savefig(QML_OUTPUT / f"figure_first50_{feature}.png", dpi=300, bbox_inches="tight",)
    plt.show()

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

for axis, feature, unit in zip(axes.flat, TARGET_NAMES, TARGET_UNITS):
    grouped_values = []
    positions = []
    tick_positions = []
    position = 1.0

    for city in ordered_cities:
        city_df = prediction_df[prediction_df["city"] == city]
        grouped_values.extend(
            [
                city_df[f"actual_bbrv3_{feature}"].to_numpy(),
                city_df[f"qnn_predicted_{feature}"].to_numpy(),
            ]
        )
        positions.extend([position, position + 0.35])
        tick_positions.append(position + 0.175)
        position += 1.2

    boxes = axis.boxplot(
        grouped_values,
        positions=positions,
        widths=0.28,
        patch_artist=True,
        showfliers=False,
    )

    for box_index, patch in enumerate(boxes["boxes"]):
        patch.set_alpha(0.55 if box_index % 2 == 0 else 0.9)

    axis.set_xticks(tick_positions)
    axis.set_xticklabels(ordered_cities, rotation=25, ha="right")
    axis.set_ylabel(unit)
    axis.set_title(feature.replace("_", " ").title())
    axis.grid(axis="y", alpha=0.3)

fig.suptitle("Recorded BBRv3 versus QNN-predicted next-interval measurements by city")
fig.text(
    0.5,
    0.01,
    "Within each city: first box = recorded BBRv3; second box = QNN prediction.",
    ha="center",
)
fig.tight_layout(rect=[0, 0.035, 1, 0.96])
fig.savefig(
    QML_OUTPUT / "figure_qnn_city_boxplots.png",
    dpi=300,
    bbox_inches="tight",
)
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(12, 10))

for axis, feature, unit in zip(axes.flat, TARGET_NAMES, TARGET_UNITS):
    actual = prediction_df[f"actual_bbrv3_{feature}"].to_numpy()
    predicted = prediction_df[f"qnn_predicted_{feature}"].to_numpy()
    lower = float(min(actual.min(), predicted.min()))
    upper = float(max(actual.max(), predicted.max()))

    axis.scatter(actual, predicted, alpha=0.45, s=18)
    axis.plot([lower, upper], [lower, upper], linestyle="--", linewidth=1)
    axis.set_xlabel(f"Recorded BBRv3 ({unit})")
    axis.set_ylabel(f"QNN predicted ({unit})")
    axis.set_title(feature.replace("_", " ").title())
    axis.grid(alpha=0.3)

fig.suptitle("Recorded BBRv3 versus QNN-predicted next-interval measurements")
fig.tight_layout(rect=[0, 0, 1, 0.96])
fig.savefig(
    QML_OUTPUT / "figure_qnn_actual_vs_predicted_scatter.png",
    dpi=300,
)
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(12, 9))

for axis, feature, unit in zip(axes.flat, TARGET_NAMES, TARGET_UNITS):
    residual = (
        prediction_df[f"actual_bbrv3_{feature}"].to_numpy()
        - prediction_df[f"qnn_predicted_{feature}"].to_numpy()
    )

    axis.hist(residual, bins=30, alpha=0.8)
    axis.axvline(0.0, linestyle="--", linewidth=1)
    axis.set_xlabel(f"Recorded - predicted ({unit})")
    axis.set_ylabel("Frequency")
    axis.set_title(feature.replace("_", " ").title())
    axis.grid(axis="y", alpha=0.3)

fig.suptitle("QNN residual distributions on held-out BBRv3 test runs")
fig.tight_layout(rect=[0, 0, 1, 0.96])
fig.savefig(
    QML_OUTPUT / "figure_qnn_residual_distributions.png",
    dpi=300,
)
plt.show()